### ISSUE TITLE
Problem with the last version of Consul

### ISSUE THREAD

**Issue by globtroter** [amirkibbar/red-apple#1]
There is integration error with the latest version of Consul. Your plugin reports problem in task startConsul.
This task start with error. In fact, the consul server instance has been started, but not completely (without ui extension). Internally REST call to consul service reports 404 status. 
The bypass is to point exact version 0.5.1 instead of current (0.6.x).

**Comment by amirkibbar** [comment]
looks like the UI package of 0.6.x changed its structure - instead of dist/<some-files> all files are not at the root of the zip. I made the necessary changes in a backwards compatible way - version 0.1.7 should work for both 0.5.x and 0.6.x versions
