### ISSUE TITLE
Unable to stop consul

### ISSUE THREAD

**Issue by ptriboll** [amirkibbar/red-apple#3]
After exxecuting stopConsul gradle task from IntelliJ IDEA or command line, consul server still running:
web page on port 8500 is usable
Anyway executing "wmic process where (name like "%%consul%%") delete" from command line stop it.

**Comment by ptriboll** [comment]
It seems there is an issue in StopConsulTask: there is no execute call of StopAction

**Comment by amirkibbar** [comment]
@ptriboll - I've added the missing execute() call, sorry about that...
